# Generated by Django 4.2.1 on 2023-05-07 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaModel',
            fields=[
                ('cat_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('cat_nome', models.CharField(max_length=35, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoModel',
            fields=[
                ('prod_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('prod_nome', models.CharField(max_length=30, null=True)),
                ('prod_estoque', models.PositiveIntegerField(null=True)),
                ('prod_preco', models.FloatField(null=True)),
                ('prod_categoria_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='produtos.categoriamodel')),
            ],
        ),
    ]
