# Generated by Django 4.2.1 on 2023-05-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtomodel',
            name='prod_foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
