# Generated by Django 4.2.1 on 2023-05-09 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0002_produtomodel_prod_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprarModel',
            fields=[
                ('comp_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('comp_quanteidade', models.PositiveIntegerField(null=True)),
                ('comp_produto_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='produtos.produtomodel')),
                ('comp_usuario_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
