# Generated by Django 4.2.1 on 2023-05-09 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0004_alter_comprarmodel_comp_quanteidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprarmodel',
            name='comp_produto_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='produtos.produtomodel'),
        ),
        migrations.AlterField(
            model_name='comprarmodel',
            name='comp_usuario_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
