# Generated by Django 4.2.1 on 2023-05-09 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_alter_comprarmodel_comp_produto_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprarmodel',
            name='comp_quanteidade',
        ),
    ]
