# Generated by Django 4.2.1 on 2023-05-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_comprarmodel_comp_quanteidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprarmodel',
            old_name='comp_quanteidade',
            new_name='comp_quantidade',
        ),
    ]
